// ============================================================================
// File: resource.h
// Description: Resource identifiers for NetworkMonitor
// Author: NetworkMonitor Project
// Note: This file is typically auto-generated by Visual Studio Resource Editor
// ============================================================================

#ifndef NETWORK_MONITOR_RESOURCE_H
#define NETWORK_MONITOR_RESOURCE_H

// ============================================================================
// ICON RESOURCES
// ============================================================================

#define IDI_APP_ICON                    101
#define IDI_TRAY_IDLE                   102
#define IDI_TRAY_ACTIVE                 103
#define IDI_TRAY_HIGH                   104

// Optional dark-variant icons (fallback to normal icons if resources not present)
#define IDI_APP_ICON_DARK               105
#define IDI_TRAY_IDLE_DARK              106
#define IDI_TRAY_ACTIVE_DARK            107
#define IDI_TRAY_HIGH_DARK              108

// ============================================================================
// MENU RESOURCES
// ============================================================================

#define IDR_TRAY_MENU                   201
#define IDR_UPDATE_MENU                 202

// ============================================================================
// MENU ITEM IDS
// ============================================================================

#define IDM_SETTINGS                    1001
#define IDM_ABOUT                       1002
#define IDM_EXIT                        1003
#define IDM_AUTOSTART                   1004
#define IDM_UPDATE_FAST                 1005
#define IDM_UPDATE_NORMAL               1006
#define IDM_UPDATE_SLOW                 1007
#define IDM_SHOW_TASKBAR_OVERLAY        1008 
#define IDM_DASHBOARD                   1009

// ============================================================================
// DIALOG RESOURCES
// ============================================================================

#define IDD_ABOUT_DIALOG                301
#define IDD_SETTINGS_DIALOG             302
#define IDD_DASHBOARD_DIALOG            303
#define IDD_HISTORY_MANAGE_DIALOG       304
#define IDD_MESSAGE_DIALOG              305

// ============================================================================
// STRING RESOURCES
// ============================================================================

#define IDS_APP_TITLE                   401
#define IDS_ERROR_INIT                  402
#define IDS_ERROR_NETWORK               403
#define IDS_ERROR_ALREADY_RUNNING       404
#define IDS_ERR_REGISTER_WINDOW_CLASS   405
#define IDS_ERR_CREATE_WINDOW           406
#define IDS_ERR_INIT_TRAY_ICON          407
#define IDS_ERR_INIT_TASKBAR_OVERLAY    408
#define IDS_ERR_START_NETWORK_MONITOR   409
#define IDS_ERR_LOAD_APP_ICON           410
#define IDS_ERR_CREATE_TRAY_ICON        411
#define IDS_MENU_UPDATE_INTERVAL        412
#define IDS_MENU_UPDATE_FAST            413
#define IDS_MENU_UPDATE_NORMAL          414
#define IDS_MENU_UPDATE_SLOW            415
#define IDS_MENU_AUTOSTART              416
#define IDS_MENU_TASKBAR_OVERLAY        417
#define IDS_MENU_SETTINGS               418
#define IDS_MENU_DASHBOARD              419
#define IDS_MENU_ABOUT                  420
#define IDS_MENU_EXIT                   421
#define IDS_DASHBOARD_COL_TIME          422
#define IDS_DASHBOARD_COL_INTERFACE     423
#define IDS_DASHBOARD_COL_DOWN          424
#define IDS_DASHBOARD_COL_UP            425
#define IDS_INTERVAL_FAST               426
#define IDS_INTERVAL_NORMAL             427
#define IDS_INTERVAL_SLOW               428
#define IDS_UNIT_BYTES_PER_SECOND       429
#define IDS_UNIT_KILOBYTES_PER_SECOND   430
#define IDS_UNIT_MEGABYTES_PER_SECOND   431
#define IDS_UNIT_MEGABITS_PER_SECOND    432
#define IDS_ALL_INTERFACES              433
#define IDS_AGGREGATED_STATS            434
#define IDS_OVERLAY_DOWN_PREFIX         435
#define IDS_OVERLAY_UP_PREFIX           436
#define IDS_ABOUT_TITLE                 437
#define IDS_ABOUT_VERSION_LABEL         438
#define IDS_ABOUT_BODY                  439
#define IDS_HISTORY_MANAGE_TITLE        440
#define IDS_HISTORY_CONFIRM_DELETE_ALL  441
#define IDS_HISTORY_CONFIRM_TRIM_30     442
#define IDS_HISTORY_CONFIRM_TRIM_90     443
#define IDS_HISTORY_ERROR_OPERATION     444
#define IDS_HISTORY_AUTO_TRIM_NONE      445
#define IDS_HISTORY_AUTO_TRIM_7D        446
#define IDS_HISTORY_AUTO_TRIM_30D       447
#define IDS_HISTORY_AUTO_TRIM_90D       448
#define IDS_HISTORY_AUTO_TRIM_365D      449
#define IDS_LANGUAGE_SYSTEM             450
#define IDS_LANGUAGE_ENGLISH            451
#define IDS_LANGUAGE_VIETNAMESE         452
#define IDS_LANGUAGE_JAPANESE           486
#define IDS_LANGUAGE_KOREAN             487
#define IDS_LANGUAGE_CHINESE_SIMPLIFIED 488
#define IDS_SETTINGS_TITLE              453
#define IDS_SETTINGS_GROUP_GENERAL      454
#define IDS_SETTINGS_GROUP_UPDATE       455
#define IDS_SETTINGS_GROUP_NETWORK      456
#define IDS_SETTINGS_LABEL_LANGUAGE     457
#define IDS_SETTINGS_LABEL_AUTOSTART    458
#define IDS_SETTINGS_LABEL_LOGGING      459
#define IDS_SETTINGS_LABEL_INTERVAL     460
#define IDS_SETTINGS_LABEL_SPEED_UNIT   461
#define IDS_SETTINGS_LABEL_MONITOR      462
#define IDS_SETTINGS_LABEL_AUTOTRIM     463
#define IDS_DASHBOARD_TITLE             464
#define IDS_DASHBOARD_LABEL_TODAY       465
#define IDS_DASHBOARD_LABEL_THIS_MONTH  466
#define IDS_DASHBOARD_LABEL_DOWNLOAD    467
#define IDS_DASHBOARD_LABEL_UPLOAD      468
#define IDS_HISTORY_DIALOG_TITLE        469
#define IDS_HISTORY_LABEL_OPERATIONS    470
#define IDS_HISTORY_BUTTON_DELETE_ALL   471
#define IDS_HISTORY_BUTTON_KEEP_30      472
#define IDS_HISTORY_BUTTON_KEEP_90      473
#define IDS_SETTINGS_LABEL_DEBUGLOGGING 474
#define IDS_SETTINGS_BUTTON_OPEN_LOG    475
#define IDS_DASHBOARD_BUTTON_EXPORT_CSV 476
#define IDS_SETTINGS_LABEL_DARK_THEME   477
#define IDS_SETTINGS_THEME_SYSTEM       478
#define IDS_SETTINGS_THEME_LIGHT        479
#define IDS_SETTINGS_THEME_DARK         480
#define IDS_NOTIFICATION_DISCONNECTED_TITLE 481
#define IDS_NOTIFICATION_DISCONNECTED_MSG   482
#define IDS_NOTIFICATION_CONNECTED_TITLE    483
#define IDS_NOTIFICATION_CONNECTED_MSG      484
#define IDS_SETTINGS_LABEL_CONNECTION_NOTIFY 485

// Tab names
#define IDS_SETTINGS_TAB_GENERAL        489
#define IDS_SETTINGS_TAB_DISPLAY        490
#define IDS_SETTINGS_TAB_ADVANCED       491

// Button labels
#define IDS_BUTTON_OK                   492
#define IDS_BUTTON_CANCEL               493
#define IDS_BUTTON_APPLY                494
#define IDS_DASHBOARD_BUTTON_REFRESH    495
#define IDS_DASHBOARD_BUTTON_CLOSE      496
#define IDS_DASHBOARD_BUTTON_MANAGE     497

// ============================================================================
// CONTROL IDS (for dialogs)
// ============================================================================

#define IDC_STATIC                      -1
#define IDC_VERSION_TEXT                501
#define IDC_COPYRIGHT_TEXT              502
#define IDC_UPDATE_INTERVAL_COMBO       503
#define IDC_DISPLAY_UNIT_COMBO          504
#define IDC_AUTOSTART_CHECK             505
#define IDC_INTERFACE_COMBO             506
#define IDC_TODAY_DOWN                  507
#define IDC_TODAY_UP                    508
#define IDC_MONTH_DOWN                  509
#define IDC_MONTH_UP                    510
#define IDC_RECENT_LIST                 511
#define IDC_ENABLE_LOGGING_CHECK        512
#define IDC_DASHBOARD_REFRESH           513
#define IDC_HISTORY_DELETE_ALL          514
#define IDC_HISTORY_KEEP_30             515
#define IDC_HISTORY_KEEP_90             516
#define IDC_HISTORY_MANAGE              517
#define IDC_HISTORY_AUTO_TRIM_COMBO     518
#define IDC_DASHBOARD_CHART             519
#define IDC_LANGUAGE_COMBO              520
#define IDC_SETTINGS_GROUP_GENERAL      521
#define IDC_SETTINGS_GROUP_UPDATE       522
#define IDC_SETTINGS_GROUP_NETWORK      523
#define IDC_SETTINGS_LABEL_LANGUAGE     524
#define IDC_SETTINGS_LABEL_INTERVAL     525
#define IDC_SETTINGS_LABEL_SPEED_UNIT   526
#define IDC_SETTINGS_LABEL_MONITOR      527
#define IDC_SETTINGS_LABEL_AUTOTRIM     528
#define IDC_DASHBOARD_LABEL_TODAY       529
#define IDC_DASHBOARD_LABEL_DOWNLOAD_T  530
#define IDC_DASHBOARD_LABEL_UPLOAD_T    531
#define IDC_DASHBOARD_LABEL_MONTH       532
#define IDC_DASHBOARD_LABEL_DOWNLOAD_M  533
#define IDC_DASHBOARD_LABEL_UPLOAD_M    534
#define IDC_HISTORY_LABEL_OPERATIONS    535
#define IDC_DEBUG_LOGGING_CHECK         536
#define IDC_SETTINGS_BUTTON_OPEN_LOG    537
#define IDC_DASHBOARD_BUTTON_EXPORT     538
#define IDC_DARK_THEME_CHECK            539
#define IDC_MESSAGE_ICON                540
#define IDC_MESSAGE_TEXT                541
#define IDC_SETTINGS_LABEL_THEME        542
#define IDC_THEME_MODE_COMBO            543
#define IDC_CONNECTION_NOTIFY_CHECK     544
#define IDC_SETTINGS_GROUP_ADVANCED     545
#define IDC_PING_TARGET_EDIT            546
#define IDC_PING_INTERVAL_COMBO         547
#define IDC_HOTKEY_COMBO                548
#define IDC_OVERLAY_FONT_SIZE_COMBO     549
#define IDC_OVERLAY_COLOR_COMBO         550
#define IDC_SETTINGS_TAB                551
#define IDC_DISPLAY_UNIT_LABEL          552
#define IDC_FONT_SIZE_LABEL             553
#define IDC_OVERLAY_COLOR_LABEL         554
#define IDC_HISTORY_TRIM_LABEL          555
#define IDC_PING_TARGET_LABEL           556
#define IDC_PING_INTERVAL_LABEL         557
#define IDC_HOTKEY_LABEL                558
#define IDC_SETTINGS_BUTTON_APPLY       559

// ============================================================================
// STANDARD DIALOG IDS
// ============================================================================

#ifndef IDOK
#define IDOK                            1
#endif

#ifndef IDCANCEL
#define IDCANCEL                        2
#endif

// Custom dialog result for Apply with reopen
#define IDAPPLY_REOPEN                  100

// ============================================================================
// Next default values for new objects
// ============================================================================

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#endif // NETWORK_MONITOR_RESOURCE_H
