// ============================================================================
// File: resource.h
// Description: Resource identifiers for NetworkMonitor
// Author: NetworkMonitor Project
// Note: This file is typically auto-generated by Visual Studio Resource Editor
// ============================================================================

#ifndef NETWORK_MONITOR_RESOURCE_H
#define NETWORK_MONITOR_RESOURCE_H

// ============================================================================
// ICON RESOURCES
// ============================================================================

#define IDI_APP_ICON                    101
#define IDI_TRAY_IDLE                   102
#define IDI_TRAY_ACTIVE                 103
#define IDI_TRAY_HIGH                   104

// ============================================================================
// MENU RESOURCES
// ============================================================================

#define IDR_TRAY_MENU                   201
#define IDR_UPDATE_MENU                 202

// ============================================================================
// MENU ITEM IDS
// ============================================================================

#define IDM_SETTINGS                    1001
#define IDM_ABOUT                       1002
#define IDM_EXIT                        1003
#define IDM_AUTOSTART                   1004
#define IDM_UPDATE_FAST                 1005
#define IDM_UPDATE_NORMAL               1006
#define IDM_UPDATE_SLOW                 1007
#define IDM_SHOW_TASKBAR_OVERLAY        1008 

// ============================================================================
// DIALOG RESOURCES
// ============================================================================

#define IDD_ABOUT_DIALOG                301
#define IDD_SETTINGS_DIALOG             302

// ============================================================================
// STRING RESOURCES
// ============================================================================

#define IDS_APP_TITLE                   401
#define IDS_ERROR_INIT                  402
#define IDS_ERROR_NETWORK               403

// ============================================================================
// CONTROL IDS (for dialogs)
// ============================================================================

#define IDC_STATIC                      -1
#define IDC_VERSION_TEXT                501
#define IDC_COPYRIGHT_TEXT              502
#define IDC_UPDATE_INTERVAL_COMBO       503
#define IDC_DISPLAY_UNIT_COMBO          504
#define IDC_AUTOSTART_CHECK             505
#define IDC_INTERFACE_COMBO             506

// ============================================================================
// STANDARD DIALOG IDS
// ============================================================================

#ifndef IDOK
#define IDOK                            1
#endif

#ifndef IDCANCEL
#define IDCANCEL                        2
#endif

// ============================================================================
// Next default values for new objects
// ============================================================================

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#endif // NETWORK_MONITOR_RESOURCE_H
